### ISSUE TITLE
provide RouteAPI

### ISSUE THREAD

**Issue by finnge** [neuro-inclusive-transit/backend-services#1]
## AKS
- [x] JSON req/response for route data
- [x] get route data from API 
- [x] Schema überlegen
- [ ] Daten in erster Form aggregieren

**Comment by leo-3108** [comment]
https://deno.land/x/oak@v12.1.0

**Comment by leo-3108** [comment]
https://deno.land/api@v1.32.1?s=URL
https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams

**Comment by leo-3108** [comment]
ToDos:
- [ ] Überdenken, ob ein GET-Request mit Header die richtige Wahl ist
- [ ] Falls nein: POST mit Body?
- [ ] Funktion zur URL-Generierung vereinfachen

**Comment by leo-3108** [comment]
https://www.figma.com/file/YXBqSf42uMzAjgqV4KJmEO/P2-%E2%80%93-Projekt-Board?type=whiteboard&node-id=492-1568&t=fnwftoMkVahqJROR-4

Aktuelle Schema der HereAPI
