### ISSUE TITLE
Fehlerhafte Response Arrival Time

### ISSUE THREAD

**Issue by finnge** [neuro-inclusive-transit/backend-services#31]
Bei Aufruf der Route API mit folgenden Parametern im Header

```json
{
  "origin": "52.520008,13.404954",
  "destination": "51.44164276123047,5.469721794128418",
  "departureTime": "2023-05-22T13:52:34.477Z"
}
```

Wird folgender Fehler zurückgemeldet:

<img width="561" alt="Bildschirm­foto 2023-05-22 um 15 54 22" src="https://github.com/neuro-inclusive-transit/backend-services/assets/19761338/7898ae28-f102-434f-adc9-72eb9d948f45">

Warum wird dieser Fehler angegeben obwohl `arrivalTime` garnicht im Request ist?

Der Fehler wurde mit folgendem Code getestet: https://github.com/neuro-inclusive-transit/mobile-app/commit/c16ea189c9d87afb2b0042e24d31dcf605692c57

**Comment by leo-3108** [comment]
Wenn ich einen Request mit genau der Parametern mit Postman absende, kommt kein Fehler.
Also vermutlich muss es am Code liegen 🤔

**Comment by leo-3108** [comment]
Kann es vielleicht sein, dass er iwie "undefined" mit in den Header packt?
